
if rival_table == nil then 
    _G.rival_table = class({})
end

rival_table.juggernaut = 
{
    ["npc_dota_hero_sven"] = {1, 2},
    ["npc_dota_hero_faceless_void"] = {3},
    ["npc_dota_hero_riki"] = {4},
    ["npc_dota_hero_storm_spirit"] = {5, 6, 7},
    ["npc_dota_hero_tiny"] = {9},
    ["npc_dota_hero_broodmother"] = {10},
    ["npc_dota_hero_sand_king"] = {11, 12},
    ["npc_dota_hero_dragon_knight"] = {13},
    ["npc_dota_hero_witch_doctor"] = {14},
    ["npc_dota_hero_skeleton_king"] = {15},
}

rival_table.juggernaut_arc = 
{
    ["npc_dota_hero_sven"] = {1, 2},
    ["npc_dota_hero_tiny"] = {3, 4},
    ["npc_dota_hero_dragon_knight"] = {5, 6},
    ["npc_dota_hero_skeleton_king"] = {7, 8},
    ["npc_dota_hero_huskar"] = {9, 10},
    ["npc_dota_hero_bristleback"] = {11, 12},
    ["npc_dota_hero_tusk"] = {13, 14},
    ["npc_dota_hero_legion_commander"] = {15, 16},
    ["npc_dota_hero_axe"] = {17, 18},
    ["npc_dota_hero_pudge"] = {19, 20},
    ["npc_dota_hero_slardar"] = {21, 22},
    ["npc_dota_hero_life_stealer"] = {23, 24},
    ["npc_dota_hero_night_stalker"] = {25, 26},
    ["npc_dota_hero_wisp"] = {27, 28},
    ["npc_dota_hero_lycan"] = {29, 30},
    ["npc_dota_hero_antimage"] = {31, 32},
    ["npc_dota_hero_phantom_lancer"] = {33, 34},
    ["npc_dota_hero_sniper"] = {35, 36},
    ["npc_dota_hero_templar_assassin"] = {37, 38},
    ["npc_dota_hero_luna"] = {39, 40},
    ["npc_dota_hero_bounty_hunter"] = {41, 42},
    ["npc_dota_hero_lone_druid"] = {43, 44},
    ["npc_dota_hero_troll_warlord"] = {45, 46},
    ["npc_dota_hero_ember_spirit"] = {47, 48},
    ["npc_dota_hero_monkey_king"] = {49, 50},
    ["npc_dota_hero_phantom_assassin"] = {51, 52},
    ["npc_dota_hero_slark"] = {53, 54},
    ["npc_dota_hero_medusa"] = {55, 56},
    ["npc_dota_hero_crystal_maiden"] = {57, 58},
    ["npc_dota_hero_lina"] = {59, 60},
    ["npc_dota_hero_tinker"] = {61, 62},
    ["npc_dota_hero_ogre_magi"] = {63, 64},
    ["npc_dota_hero_rubick"] = {65, 66},
    ["npc_dota_hero_warlock"] = {67, 68},
    ["npc_dota_hero_invoker"] = {69, 70},
    ["npc_dota_hero_winter_wyvern"] = {71, 72},
    ["npc_dota_hero_techies"] = {73},
    ["npc_dota_hero_tidehunter"] = {75, 76},
    ["npc_dota_hero_naga_siren"] = {77, 78},
    ["npc_dota_hero_puck"] = {79, 80},
    ["npc_dota_hero_dark_seer"] = {81, 82},
}



rival_table.pa_persona =
{
    ["npc_dota_hero_abaddon"] = {1},
    ["npc_dota_hero_alchemist"] = {3},
    ["npc_dota_hero_ancient_apparition"] = {5},
    ["npc_dota_hero_antimage"] = {7},
    ["npc_dota_hero_arc_warden"] = {9},
    ["npc_dota_hero_axe"] = {11},
    ["npc_dota_hero_bane"] = {13},
    ["npc_dota_hero_batrider"] = {15},
    ["npc_dota_hero_beastmaster"] = {17},
    ["npc_dota_hero_bloodseeker"] = {19},
    ["npc_dota_hero_bounty_hunter"] = {21},
    ["npc_dota_hero_brewmaster"] = {23},
    ["npc_dota_hero_bristleback"] = {25},
    ["npc_dota_hero_broodmother"] = {27},
    ["npc_dota_hero_centaur"] = {29},
    ["npc_dota_hero_chaos_knight"] = {31},
    ["npc_dota_hero_chen"] = {33},
    ["npc_dota_hero_clinkz"] = {35},
    ["npc_dota_hero_rattletrap"] = {37},
    ["npc_dota_hero_crystal_maiden"] = {39},
    ["npc_dota_hero_dark_seer"] = {41},
    ["npc_dota_hero_dark_willow"] = {43},
    ["npc_dota_hero_dawnbreaker"] = {45},
    ["npc_dota_hero_dazzle"] = {47},
    ["npc_dota_hero_death_prophet"] = {49},
    ["npc_dota_hero_disruptor"] = {51},
    ["npc_dota_hero_doom_bringer"] = {53},
    ["npc_dota_hero_dragon_knight"] = {55},
    ["npc_dota_hero_drow_ranger"] = {57, 058},
    ["npc_dota_hero_earth_spirit"] = {59},
    ["npc_dota_hero_earthshaker"] = {61},
    ["npc_dota_hero_elder_titan"] = {63},
    ["npc_dota_hero_ember_spirit"] = {65},
    ["npc_dota_hero_enchantress"] = {67},
    ["npc_dota_hero_enigma"] = {69},
    ["npc_dota_hero_faceless_void"] = {71, 72},
    ["npc_dota_hero_grimstroke"] = {73},
    ["npc_dota_hero_gyrocopter"] = {75},
    ["npc_dota_hero_hoodwink"] = {77},
    ["npc_dota_hero_huskar"] = {79},
    ["npc_dota_hero_wisp"] = {81},
    ["npc_dota_hero_invoker"] = {83, 84},
    ["npc_dota_hero_jakiro"] = {85},
    ["npc_dota_hero_juggernaut"] = {87},
    ["npc_dota_hero_keeper_of_the_light"] = {89},
    ["npc_dota_hero_kunkka"] = {91},
    ["npc_dota_hero_legion_commander"] = {93},
    ["npc_dota_hero_leshrac"] = {95},
    ["npc_dota_hero_lich"] = {97},
    ["npc_dota_hero_life_stealer"] = {99},
    ["npc_dota_hero_lina"] = {101},
    ["npc_dota_hero_lion"] = {103},
    ["npc_dota_hero_lone_druid"] = {105},
    ["npc_dota_hero_luna"] = {107},
    ["npc_dota_hero_lycan"] = {109},
    ["npc_dota_hero_magnataur"] = {111},
    ["npc_dota_hero_marci"] = {113},
    ["npc_dota_hero_mars"] = {115},
    ["npc_dota_hero_medusa"] = {117},
    ["npc_dota_hero_meepo"] = {119},
    ["npc_dota_hero_mirana"] = {121},
    ["npc_dota_hero_monkey_king"] = {123},
    ["npc_dota_hero_furion"] = {129},
    ["npc_dota_hero_nyx_assassin"] = {135},
    ["npc_dota_hero_oracle"] = {141, 142, 143, 147, 148},
    ["npc_dota_hero_pangolier"] = {145},
    ["npc_dota_hero_primal_beast"] = {153},
    ["npc_dota_hero_queenofpain"] = {161},
    ["npc_dota_hero_skywrath_mage"] = {179},
    ["npc_dota_hero_snapfire"] = {185},
    ["npc_dota_hero_techies"] = {197},
    ["npc_dota_hero_templar_assassin"] = {199},
    ["npc_dota_hero_shredder"] = {205},
    ["npc_dota_hero_tinker"] = {207},
    ["npc_dota_hero_treant"] = {211},
    ["npc_dota_hero_troll_warlord"] = {213},
    ["npc_dota_hero_tusk"] = {215},
    ["npc_dota_hero_undying"] = {219},
    ["npc_dota_hero_vengefulspirit"] = {223, 224},
    ["npc_dota_hero_void_spirit"] = {231},
    ["npc_dota_hero_warlock"] = {233},
    ["npc_dota_hero_weaver"] = {235},
    ["npc_dota_hero_windrunner"] = {237},
    ["npc_dota_hero_winter_wyvern"] = {239},
    ["npc_dota_hero_witch_doctor"] = {241},
    ["npc_dota_hero_skeleton_king"] = {243},
    ["npc_dota_hero_zuus"] = {245},

} 



rival_table.legion = 
{
    ["npc_dota_hero_underlord"] = {1, 2, 3, 4},
    ["npc_dota_hero_kunkka"] = {5},
    ["npc_dota_hero_medusa"] = {6},
    ["npc_dota_hero_luna"] = {7},
    ["npc_dota_hero_axe"] = {8},
    ["npc_dota_hero_rubick"] = {9},
    ["npc_dota_hero_faceless_void"] = {10},
    ["npc_dota_hero_chen"] = {11},
    ["npc_dota_hero_doom_bringer"] = {12, 13, 27},
    ["npc_dota_hero_shadow_demon"] = {12, 13, 27},
    ["npc_dota_hero_nevermore"] = {12, 13, 27},
    ["npc_dota_hero_terrorblade"] = {12, 13, 17, 27},
    ["npc_dota_hero_dark_seer"] = {14, 15},
    ["npc_dota_hero_abaddon"] = {16},
    ["npc_dota_hero_techies"] = {18},
    ["npc_dota_hero_phoenix"] = {19},
    ["npc_dota_hero_skywrath_mage"] = {20},
    ["npc_dota_hero_elder_titan"] = {21},
    ["npc_dota_hero_undying"] = {22, 23},
    ["npc_dota_hero_riki"] = {24},
    ["npc_dota_hero_templar_assassin"] = {24},
    ["npc_dota_hero_phantom_assassin"] = {24},
    ["npc_dota_hero_nyx_assassin"] = {24},
    ["npc_dota_hero_bounty_hunter"] = {24},
    ["npc_dota_hero_puck"] = {26},
    ["npc_dota_hero_winter_wyvern"] = {26},
    ["npc_dota_hero_dragon_knight"] = {26},
    ["npc_dota_hero_jakiro"] = {26},
    ["npc_dota_hero_arc_warden"] = {36},
}




rival_table.legion_arc = 
{
    ["npc_dota_hero_underlord"] = {1, 2, 3, 4},
    ["npc_dota_hero_kunkka"] = {5},
    ["npc_dota_hero_medusa"] = {6},
    ["npc_dota_hero_luna"] = {7},
    ["npc_dota_hero_axe"] = {8},
    ["npc_dota_hero_rubick"] = {9},
    ["npc_dota_hero_faceless_void"] = {10},
    ["npc_dota_hero_chen"] = {11},
    ["npc_dota_hero_doom_bringer"] = {12, 13, 27},
    ["npc_dota_hero_shadow_demon"] = {12, 13, 27},
    ["npc_dota_hero_nevermore"] = {12, 13, 27},
    ["npc_dota_hero_terrorblade"] = {12, 13, 17, 27},
    ["npc_dota_hero_dark_seer"] = {14, 15},
    ["npc_dota_hero_abaddon"] = {16},
    ["npc_dota_hero_techies"] = {18},
    ["npc_dota_hero_phoenix"] = {19},
    ["npc_dota_hero_skywrath_mage"] = {20},
    ["npc_dota_hero_elder_titan"] = {21},
    ["npc_dota_hero_undying"] = {22, 23},
    ["npc_dota_hero_riki"] = {24},
    ["npc_dota_hero_templar_assassin"] = {24},
    ["npc_dota_hero_phantom_assassin"] = {24},
    ["npc_dota_hero_nyx_assassin"] = {24},
    ["npc_dota_hero_bounty_hunter"] = {24},
    ["npc_dota_hero_puck"] = {26},
    ["npc_dota_hero_winter_wyvern"] = {26},
    ["npc_dota_hero_dragon_knight"] = {26},
    ["npc_dota_hero_jakiro"] = {26},
    ["npc_dota_hero_arc_warden"] = {36},
}




rival_table.nevermore = 
{
    ["npc_dota_hero_leshrac"] = {1},
    ["npc_dota_hero_doom_bringer"] = {2, 3, 4},
    ["npc_dota_hero_shadow_demon"] = {5, 6, 7, 8, 9, 10},
    ["npc_dota_hero_terrorblade"] = {11, 12},
    ["npc_dota_hero_windrunner"] = {13},

}


rival_table.nevermore_arc = 
{
    ["npc_dota_hero_leshrac"] = {1},
    ["npc_dota_hero_doom_bringer"] = {2, 3, 4},
    ["npc_dota_hero_shadow_demon"] = {5, 6, 7, 8, 9, 10},
    ["npc_dota_hero_terrorblade"] = {11, 12},
    ["npc_dota_hero_windrunner"] = {13},

}


rival_table.razor_arc = 
{
    ["npc_dota_hero_"] = {},
}    


rival_table.razor = 
{

    ["npc_dota_hero_storm_spirit"] = {1, 2},
    ["npc_dota_hero_zuus"] = {3, 4},
    ["npc_dota_hero_rattletrap"] = {5},
    ["npc_dota_hero_sand_king"] = {6},
    ["npc_dota_hero_tinker"] = {7, 8},
    ["npc_dota_hero_earthshaker"] = {9},
    ["npc_dota_hero_weaver"] = {10},
    ["npc_dota_hero_morphling"] = {11, 12},
    ["npc_dota_hero_furion"] = {13},
    ["npc_dota_hero_jakiro"] = {14, 15},
    ["npc_dota_hero_nevermore"] = {16},
    ["npc_dota_hero_magnataur"] = {17, 18, 19},
    ["npc_dota_hero_leshrac"] = {20},
}    


rival_table.blank = 
{
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},
    ["npc_dota_hero_"] = {},    
}