return
{
    [7212] = {
        ['item_id'] =7212,
        ['name'] ='Bloodfeather Wings',
        ['icon'] ='econ/items/queenofpain/bloody_raven_wings/bloody_raven_wings',
        ['price'] = 1000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/bloody_raven_wings/bloody_raven_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'rare',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_bloody_raven_wings/qop_bloody_raven_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
    },
    [12322] = {
        ['item_id'] =12322,
        ['name'] ='Bloodfeather Feast',
        ['icon'] ='econ/items/queenofpain/qop_ti8_weapon/qop_ti8_weapon',
        ['price'] = 1000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['MaterialGroupItem'] = "0",
        ['ItemModel'] ='models/items/queenofpain/qop_ti8_weapon/qop_ti8_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_queenofpain_ti_8_weapon_custom",
        ['sets'] = 'rare',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_ti8_immortal/queen_ti8_dagger_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [3] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_blade"
                    },
                    [4] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_endblade_01"
                    },
                    [5] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_endblade_02"
                    },
                    [6] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_a"
                    },
                    [7] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_b"
                    },
                }
            },
        },
    },
    [12337] = {
        ['item_id'] =12337,
        ['name'] ='Golden Bloodfeather Feast',
        ['icon'] ='econ/items/queenofpain/qop_ti8_weapon/qop_ti8_weapon1',
        ['price'] = 2000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['MaterialGroupItem'] = "1",
        ['ItemModel'] ='models/items/queenofpain/qop_ti8_weapon/qop_ti8_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_queenofpain_ti_8_weapon_custom_golden",
        ['sets'] = 'rare',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_ti8_immortal/queen_ti8_dagger_golden_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [3] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_blade"
                    },
                    [4] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_endblade_01"
                    },
                    [5] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_endblade_02"
                    },
                    [6] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_a"
                    },
                    [7] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_b"
                    },
                }
            },
        },
    },

    [23697] = 
    {
        ['item_id'] =23697,
        ['name'] ='Bloodfeather Finery',
        ['icon'] ='econ/items/queenofpain/qop_2022_immortal/qop_2022_immortal',
        ['price'] = 4000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroupItem'] = "default",
        ['ItemModel'] ='models/items/queenofpain/qop_2022_immortal/qop_2022_immortal.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{23697, "#e53437"}, {2369701, "#5f9aea"}},
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_queenofpain_immortal_custom",
        ['sets'] = 'rare',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_2022_immortal/queen_2022_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
    },

    [24100] = 
    {
        ['item_id'] =24100,
        ['name'] ='Bloodfeather Boots',
        ['icon'] ='econ/items/queenofpain/qop_2022_immortal/qop_2022_immortal_legs',
        ['price'] = 4001,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/qop_2022_immortal/qop_2022_immortal_legs.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'legs',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'rare',
    },

    [2369701] = 
    {
        ['item_id'] =2369701,
        ['name'] ='Bloodfeather Finery',
        ['icon'] ='econ/items/queenofpain/qop_2022_immortal/qop_2022_immortal_style1',
        ['price'] = 4000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroupItem'] = "1",
        ['ItemModel'] ='models/items/queenofpain/qop_2022_immortal/qop_2022_immortal.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{23697, "#e53437"}, {2369701, "#5f9aea"}},
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_queenofpain_immortal_custom_v2",
        ['sets'] = 'rare',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_2022_immortal/queen_2022_ambient_blue.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
    },

    [5157] = {
        ['item_id'] =5157,
        ['name'] ='Shade of Anguish',
        ['icon'] ='econ/items/queenofpain/shadeofagony/shadeofagony',
        ['price'] = 600,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/shadeofagony/shadeofagony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'maze_of_anguish',
    },
    [5159] = {
        ['item_id'] =5159,
        ['name'] ='Guard of Anguish',
        ['icon'] ='econ/items/queenofpain/armorofagony/armorofagony',
        ['price'] = 600,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/armorofagony/armorofagony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'maze_of_anguish',
    },
    [6839] = {
        ['item_id'] =6839,
        ['name'] ='Crimson Agony',
        ['icon'] ='econ/items/queenofpain/sanguine_weapon/sanguine_weapon',
        ['price'] = 600,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/sanguine_weapon/sanguine_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'maze_of_anguish',
    },

    [5162] = {
        ['item_id'] =5162,
        ['name'] ='Maze of Anguish',
        ['icon'] ='econ/items/queenofpain/wingsofagony/wingsofagony',
        ['price'] = 600,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/wingsofagony/wingsofagony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'maze_of_anguish',
    },

    

    [7750] = {
        ['item_id'] =7750,
        ['name'] ='Veil of the Parasols Sting',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_wings/regalia_of_the_ill_wind_wings',
        ['price'] = 200,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_wings/regalia_of_the_ill_wind_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'parsols_sting',
    },
    [7753] = {
        ['item_id'] =7753,
        ['name'] ='Ancipitous Strike of the Parasols Sting',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_weapon/regalia_of_the_ill_wind_weapon',
        ['price'] = 200,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_weapon/regalia_of_the_ill_wind_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'parsols_sting',
    },
    [7754] = {
        ['item_id'] =7754,
        ['name'] ='Jabot of the Parasols Sting',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_shoulder/regalia_of_the_ill_wind_shoulder',
        ['price'] = 300,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_shoulder/regalia_of_the_ill_wind_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'parsols_sting',
    },
    [7755] = {
        ['item_id'] =7755,
        ['name'] ='Ferronniere of the Parasols Sting',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_head/regalia_of_the_ill_wind_head',
        ['price'] = 300,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_head/regalia_of_the_ill_wind_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'parsols_sting',
    },



    [12930] = 
    {
        ['item_id'] =12930,
        ['name'] ='Eminence of Ristul',
        ['icon'] ='econ/items/queenofpain/queenofpain_arcana/queenofpain_arcana',
        ['price'] = 15000,
        ['sale'] = 0,
        ['sale_price'] = 0,
        ['is_exclusive'] = 1,
        ['HeroModel'] = "models/items/queenofpain/queenofpain_arcana/queenofpain_arcana.vmdl",
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = "default",
        ['MaterialGroupItem'] = "default",
        ['ItemModel'] ='models/items/queenofpain/queenofpain_arcana/queenofpain_arcana_modest_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{12930, "#e53437"}, {1293001, "#5f9aea"}},
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_queenofpain_arcana_custom_1",
        ['sets'] = 'queenofpain_arcana',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_wings_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_hot_l"
                    },
                }
            },
        },
        ['ParticlesHero'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_whip_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [0] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_end", "hero",
                    },
                }
            },
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_feet_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
    },
    [1293001] = 
    {
        ['item_id'] =1293001,
        ['name'] ='Eminence of Ristul',
        ['icon'] ='econ/items/queenofpain/queenofpain_arcana/queenofpain_arcana_style1',
        ['price'] = 15000,
        ['HeroModel'] = "models/items/queenofpain/queenofpain_arcana/queenofpain_arcana.vmdl",
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = "1",
        ['is_exclusive'] = 1,
        ['MaterialGroupItem'] = "1",
        ['ItemModel'] ='models/items/queenofpain/queenofpain_arcana/queenofpain_arcana_modest_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{12930, "#e53437"}, {1293001, "#5f9aea"}},
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_queenofpain_arcana_custom_2",
        ['sets'] = 'queenofpain_arcana',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_wings_v2_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_hot_l"
                    },
                }
            },
        },
        ['ParticlesHero'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_whip_ambient_v2.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [0] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_end", "hero",
                    },
                }
            },
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_feet_ambient_v2.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
    },

    [13768] = 
    {
           ['item_id'] =13768,
           ['name'] ='Raiments of the Eminence of Ristul',
           ['icon'] ='econ/items/queenofpain/queenofpain_arcana/queenofpain_arcana_armor_legacy',
           ['price'] = 0,
           ['HeroModel'] = nil,
           ['ArcanaAnim'] = nil,
           ['MaterialGroup'] = nil,
           ['ItemModel'] ='models/items/queenofpain/queenofpain_arcana/queenofpain_arcana_armor_legacy.vmdl',
           ['SetItems'] = nil,
           ['hide'] = 0,
           ['OtherItemsBundle'] = nil,
           ['SlotType'] = 'shoulder',
           ['RemoveDefaultItemsList'] = nil,
           ['Modifier'] = nil,
           ['sets'] = 'queenofpain_arcana',
    },
    [13769] = 
    {
        ['item_id'] =13769,
        ['name'] ='Crown of the Eminence of Ristul',
        ['icon'] ='econ/items/queenofpain/queenofpain_arcana/queenofpain_arcana_head',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['MaterialGroupItem'] = "default",
        ['ItemModel'] ='models/items/queenofpain/queenofpain_arcana/queenofpain_arcana_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{13769, "#e53437"}, {1376901, "#5f9aea"}},
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'queenofpain_arcana',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_head_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_l", "hero"
                    },
                    [3] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_r", "hero"
                    },
                }
            },
        },
    },
    [1376901] = 
    {
        ['item_id'] =1376901,
        ['name'] ='Crown of the Eminence of Ristul',
        ['icon'] ='econ/items/queenofpain/queenofpain_arcana/queenofpain_arcana_head',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['MaterialGroupItem'] = "1",
        ['ItemModel'] ='models/items/queenofpain/queenofpain_arcana/queenofpain_arcana_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{13769, "#e53437"}, {1376901, "#5f9aea"}},
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'queenofpain_arcana',
        ['ParticlesItems'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_head_ambient_v2.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_l", "hero"
                    },
                    [3] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_r", "hero"
                    },
                }
            },
        },
    },
    [13770] = 
    {
        ['item_id'] =13770,
        ['name'] ='Grace of the Eminence of Ristul',
        ['icon'] ='econ/items/queenofpain/queenofpain_arcana/queenofpain_arcana_dagger',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['MaterialGroupItem'] = "default",
        ['ItemModel'] ='models/items/queenofpain/queenofpain_arcana/queenofpain_arcana_dagger.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{13770, "#e53437"}, {1377001, "#5f9aea"}},
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'queenofpain_arcana',
        ['ParticlesHero'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_blade_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
    },
    [1377001] = 
    {
        ['item_id'] =1377001,
        ['name'] ='Grace of the Eminence of Ristul',
        ['icon'] ='econ/items/queenofpain/queenofpain_arcana/queenofpain_arcana_dagger',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['MaterialGroupItem'] = "1",
        ['ItemModel'] ='models/items/queenofpain/queenofpain_arcana/queenofpain_arcana_dagger.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{13770, "#e53437"}, {1377001, "#5f9aea"}},
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'queenofpain_arcana',
        ['ParticlesHero'] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/queen_of_pain/qop_arcana/qop_arcana_blade_ambient_v2.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
    },

    [8232] = {
            ['item_id'] =8232,
            ['name'] ='Span of Delightful Affliction',
            ['icon'] ='econ/items/queenofpain/esl_demonic_affliction_back/esl_demonic_affliction_back',
            ['price'] = 600,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/queenofpain/esl_demonic_affliction_back/esl_demonic_affliction_back.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'back',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'delightfull_qop',
    },
    [8233] = {
            ['item_id'] =8233,
            ['name'] ='Dagger of Delightful Affliction',
            ['icon'] ='econ/items/queenofpain/esl_demonic_affliction_weapon/esl_demonic_affliction_weapon',
            ['price'] = 600,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/queenofpain/esl_demonic_affliction_weapon/esl_demonic_affliction_weapon.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'weapon',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'delightfull_qop',
    },
    [8107] = {
            ['item_id'] =8107,
            ['name'] ='Prongs of Delightful Affliction',
            ['icon'] ='econ/items/queenofpain/esl_demonic_affliction_head/esl_demonic_affliction_head',
            ['price'] = 600,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/queenofpain/esl_demonic_affliction_head/esl_demonic_affliction_head.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'head',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'delightfull_qop',
    },
    [8231] = {
            ['item_id'] =8231,
            ['name'] ='Mantle of Delightful Affliction',
            ['icon'] ='econ/items/queenofpain/esl_demonic_affliction_shoulder/esl_demonic_affliction_shoulder',
            ['price'] = 600,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/queenofpain/esl_demonic_affliction_shoulder/esl_demonic_affliction_shoulder.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'shoulder',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'delightfull_qop',
    },
}

--[[

[9858] = {
        ['item_id'] =9858,
        ['name'] ='Form of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_shoulder/ti8_qop_bat_queen_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_shoulder/ti8_qop_bat_queen_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'abyssal_kin',
    },
    [9859] = {
        ['item_id'] =9859,
        ['name'] ='Crown of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_head/ti8_qop_bat_queen_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_head/ti8_qop_bat_queen_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'abyssal_kin',
    },
    [9860] = {
        ['item_id'] =9860,
        ['name'] ='Blade of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_weapon/ti8_qop_bat_queen_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_weapon/ti8_qop_bat_queen_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'abyssal_kin',
    },
    [23743] = {
        ['item_id'] =23743,
        ['name'] ='Abyssal Kin Legs',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_legs/ti8_qop_bat_queen_legs',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_legs/ti8_qop_bat_queen_legs.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'legs',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'abyssal_kin',
    },
    [9863] = {
        ['item_id'] =9863,
        ['name'] ='Wings of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_back/ti8_qop_bat_queen_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_back/ti8_qop_bat_queen_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'abyssal_kin',
    },
[6683] = {
        ['item_id'] =6683,
        ['name'] ='Tormentors Diadem',
        ['icon'] ='econ/items/queenofpain/tormentorsdiadem_head/tormentorsdiadem_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/tormentorsdiadem_head/tormentorsdiadem_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [7750] = {
        ['item_id'] =7750,
        ['name'] ='Veil of the Parasols Sting',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_wings/regalia_of_the_ill_wind_wings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_wings/regalia_of_the_ill_wind_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [7753] = {
        ['item_id'] =7753,
        ['name'] ='Ancipitous Strike of the Parasols Sting',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_weapon/regalia_of_the_ill_wind_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_weapon/regalia_of_the_ill_wind_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [7754] = {
        ['item_id'] =7754,
        ['name'] ='Jabot of the Parasols Sting ',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_shoulder/regalia_of_the_ill_wind_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_shoulder/regalia_of_the_ill_wind_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [7755] = {
        ['item_id'] =7755,
        ['name'] ='Ferronniere of the Parasols Sting ',
        ['icon'] ='econ/items/queenofpain/regalia_of_the_ill_wind_head/regalia_of_the_ill_wind_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/regalia_of_the_ill_wind_head/regalia_of_the_ill_wind_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [5296] = {
        ['item_id'] =5296,
        ['name'] ='Chained Wings',
        ['icon'] ='econ/items/queenofpain/unchained_tormented_wings/unchained_tormented_wings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/unchained_tormented_wings/unchained_tormented_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [4480] = {
        ['item_id'] =4480,
        ['name'] ='Wings of the Ruby Web',
        ['icon'] ='econ/items/queenofpain/anuxi_ruby_web_wings/anuxi_ruby_web_wings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/anuxi_ruby_web_wings/anuxi_ruby_web_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [7527] = {
        ['item_id'] =7527,
        ['name'] ='Wings of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/dotapit_s3_abyssal_temptress_back/dotapit_s3_abyssal_temptress_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_back/dotapit_s3_abyssal_temptress_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [7528] = {
        ['item_id'] =7528,
        ['name'] ='Horns of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/dotapit_s3_abyssal_temptress_head/dotapit_s3_abyssal_temptress_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_head/dotapit_s3_abyssal_temptress_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [7529] = {
        ['item_id'] =7529,
        ['name'] ='Armor of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/dotapit_s3_abyssal_temptress_shoulder/dotapit_s3_abyssal_temptress_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_shoulder/dotapit_s3_abyssal_temptress_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [7530] = {
        ['item_id'] =7530,
        ['name'] ='Dagger of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/dotapit_s3_abyssal_temptress_weapon/dotapit_s3_abyssal_temptress_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_weapon/dotapit_s3_abyssal_temptress_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [7548] = {
        ['item_id'] =7548,
        ['name'] ='Sinners Embrace',
        ['icon'] ='econ/items/queenofpain/sinners_embrace_back/sinners_embrace_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/sinners_embrace_back/sinners_embrace_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [4517] = {
        ['item_id'] =4517,
        ['name'] ='Horns of the Wicked Succubus',
        ['icon'] ='econ/items/queenofpain/tpl_hair_lvl1/tpl_hair_lvl1',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/tpl_hair_lvl1/tpl_hair_lvl1.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [9858] = {
        ['item_id'] =9858,
        ['name'] ='Form of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_shoulder/ti8_qop_bat_queen_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_shoulder/ti8_qop_bat_queen_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [9859] = {
        ['item_id'] =9859,
        ['name'] ='Crown of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_head/ti8_qop_bat_queen_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_head/ti8_qop_bat_queen_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [9860] = {
        ['item_id'] =9860,
        ['name'] ='Blade of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_weapon/ti8_qop_bat_queen_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_weapon/ti8_qop_bat_queen_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [7189] = {
        ['item_id'] =7189,
        ['name'] ='Sash of Twilight Shade',
        ['icon'] ='econ/items/queenofpain/twilight_shade_shoulder/twilight_shade_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/twilight_shade_shoulder/twilight_shade_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [7192] = {
        ['item_id'] =7192,
        ['name'] ='Style of Twilight Shade',
        ['icon'] ='econ/items/queenofpain/twilight_shade_head/twilight_shade_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/twilight_shade_head/twilight_shade_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [6572] = {
        ['item_id'] =6572,
        ['name'] ='Wings of Searing Pain',
        ['icon'] ='econ/items/queenofpain/pw_lava_wings/queenofpain_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/pw_lava_wings/queenofpain_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [5587] = {
        ['item_id'] =5587,
        ['name'] ='Epaulette of Blight',
        ['icon'] ='econ/items/queenofpain/queenofpain_blightedagony_shoulder/queenofpain_blightedagony_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queenofpain_blightedagony_shoulder/queenofpain_blightedagony_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [5589] = {
        ['item_id'] =5589,
        ['name'] ='Shard of Blight',
        ['icon'] ='econ/items/queenofpain/queenofpain_shard_of_blighted_agony/queenofpain_shard_of_blighted_agony',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queenofpain_shard_of_blighted_agony/queenofpain_shard_of_blighted_agony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [5590] = {
        ['item_id'] =5590,
        ['name'] ='Wings of Blight',
        ['icon'] ='econ/items/queenofpain/wings_of_blighted_agony/wings_of_blighted_agony',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/wings_of_blighted_agony/wings_of_blighted_agony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [6601] = {
        ['item_id'] =6601,
        ['name'] ='Shoulders of the Dark Angel',
        ['icon'] ='econ/items/queenofpain/darkangel_shoulder/darkangel_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/darkangel_shoulder/darkangel_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [6602] = {
        ['item_id'] =6602,
        ['name'] ='Wings of the Dark Angel',
        ['icon'] ='econ/items/queenofpain/darkangel_back/darkangel_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/darkangel_back/darkangel_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [6603] = {
        ['item_id'] =6603,
        ['name'] ='Horns of the Dark Angel',
        ['icon'] ='econ/items/queenofpain/darkangel_head/darkangel_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/darkangel_head/darkangel_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [6604] = {
        ['item_id'] =6604,
        ['name'] ='Dagger of the Dark Angel',
        ['icon'] ='econ/items/queenofpain/darkangel_weapon/darkangel_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/darkangel_weapon/darkangel_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [5157] = {
        ['item_id'] =5157,
        ['name'] ='Shade of Anguish',
        ['icon'] ='econ/items/queenofpain/shadeofagony/shadeofagony',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/shadeofagony/shadeofagony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [5159] = {
        ['item_id'] =5159,
        ['name'] ='Guard of Anguish',
        ['icon'] ='econ/items/queenofpain/armorofagony/armorofagony',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/armorofagony/armorofagony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [5160] = {
        ['item_id'] =5160,
        ['name'] ='Dagger of Anguish',
        ['icon'] ='econ/items/queenofpain/daggerofagonizingpain/daggerofagonizingpain',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/daggerofagonizingpain/daggerofagonizingpain.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        
        [18161] = {
        ['item_id'] =18161,
        ['name'] ='Lineage Wings of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/ti10_dotapit_s3_abyssal_temptress_back/dotapit_s3_abyssal_temptress_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_back/ti10_dotapit_s3_abyssal_temptress_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [18162] = {
        ['item_id'] =18162,
        ['name'] ='Lineage Horns of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/ti10_dotapit_s3_abyssal_temptress_head/dotapit_s3_abyssal_temptress_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_head/dotapit_s3_abyssal_temptress_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [18163] = {
        ['item_id'] =18163,
        ['name'] ='Lineage Armor of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/ti10_dotapit_s3_abyssal_temptress_shoulder/dotapit_s3_abyssal_temptress_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_shoulder/dotapit_s3_abyssal_temptress_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [18164] = {
        ['item_id'] =18164,
        ['name'] ='Lineage Dagger of the Arch Temptress',
        ['icon'] ='econ/items/queenofpain/ti10_dotapit_s3_abyssal_temptress_weapon/dotapit_s3_abyssal_temptress_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/dotapit_s3_abyssal_temptress_weapon/dotapit_s3_abyssal_temptress_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [82] = {
        ['item_id'] =82,
        ['name'] ='Queen of Pains Wings',
        ['icon'] ='econ/heroes/queenofpain/wings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/queenofpain/wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [84] = {
        ['item_id'] =84,
        ['name'] ='Queen of Pains Hair',
        ['icon'] ='econ/heroes/queenofpain/hair',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/queenofpain/hair.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [6839] = {
        ['item_id'] =6839,
        ['name'] ='Crimson Agony',
        ['icon'] ='econ/items/queenofpain/sanguine_weapon/sanguine_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/sanguine_weapon/sanguine_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [6840] = {
        ['item_id'] =6840,
        ['name'] ='Crown of Sanguine Royalty',
        ['icon'] ='econ/items/queenofpain/sanguine_crown/sanguine_crown',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/sanguine_crown/sanguine_crown.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [6841] = {
        ['item_id'] =6841,
        ['name'] ='Wings of Royal Ascension',
        ['icon'] ='econ/items/queenofpain/sanguine_wings/sanguine_wings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/sanguine_wings/sanguine_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [6842] = {
        ['item_id'] =6842,
        ['name'] ='Vestments of Sanguine Royalty',
        ['icon'] ='econ/items/queenofpain/sanguine_shoulders/sanguine_shoulders',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/sanguine_shoulders/sanguine_shoulders.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [4664] = {
        ['item_id'] =4664,
        ['name'] ='Torment Unbound',
        ['icon'] ='econ/items/queenofpain/queenofpainhair/queenofpainhair',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queenofpainhair/queenofpainhair.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [4665] = {
        ['item_id'] =4665,
        ['name'] ='Chain of Enduring Torment',
        ['icon'] ='econ/items/queenofpain/queenchains/queenchains',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queenchains/queenchains.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [4666] = {
        ['item_id'] =4666,
        ['name'] ='Tiara of Enduring Torment',
        ['icon'] ='econ/items/queenofpain/secretqueencrown/secretqueencrown',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/secretqueencrown/secretqueencrown.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [4667] = {
        ['item_id'] =4667,
        ['name'] ='Dagger of Enduring Torment',
        ['icon'] ='econ/items/queenofpain/snakedagger/snakedagger',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/snakedagger/snakedagger.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [23697] = {
        ['item_id'] =23697,
        ['name'] ='Bloodfeather Frock',
        ['icon'] ='econ/items/queenofpain/qop_2022_immortal/qop_2022_immortal',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/qop_2022_immortal/qop_2022_immortal.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },

        
        [24200] = {
        ['item_id'] =24200,
        ['name'] ='Swarm of the Killer Queen - Wings',
        ['icon'] ='econ/items/queenofpain/queen_of_pain_wings/queen_of_pain_wings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queen_of_pain_wings/queen_of_pain_wings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
 
        
        [4962] = {
        ['item_id'] =4962,
        ['name'] ='Tear of Agony',
        ['icon'] ='econ/items/queenofpain/qop_tears_of_agony_submit/qop_tears_of_agony_submit',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/qop_tears_of_agony_submit/qop_tears_of_agony_submit.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [781] = {
        ['item_id'] =781,
        ['name'] ='Queen of Pains Legs',
        ['icon'] ='econ/heroes/queenofpain/queenofpain_legs',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/queenofpain/queenofpain_legs.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'legs',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'legs',
        },
        [24169] = {
        ['item_id'] =24169,
        ['name'] ='Swarm of the Killer Queen - Dagger',
        ['icon'] ='econ/items/queenofpain/queen_of_pain_dagger/queen_of_pain_dagger',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queen_of_pain_dagger/queen_of_pain_dagger.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [24168] = {
        ['item_id'] =24168,
        ['name'] ='Swarm of the Killer Queen - Armor',
        ['icon'] ='econ/items/queenofpain/queen_of_pain_armor/queen_of_pain_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queen_of_pain_armor/queen_of_pain_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [24167] = {
        ['item_id'] =24167,
        ['name'] ='Swarm of the Killer Queen - Head',
        ['icon'] ='econ/items/queenofpain/queen_of_pain_head/queen_of_pain_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queen_of_pain_head/queen_of_pain_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [5183] = {
        ['item_id'] =5183,
        ['name'] ='Wings of Vincere',
        ['icon'] ='econ/items/queenofpain/wings_of_vincere/wings_of_vincere',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/wings_of_vincere/wings_of_vincere.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [5184] = {
        ['item_id'] =5184,
        ['name'] ='Crown of Vincere',
        ['icon'] ='econ/items/queenofpain/crown_of_vincere/crown_of_vincere',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/crown_of_vincere/crown_of_vincere.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [5185] = {
        ['item_id'] =5185,
        ['name'] ='Guards of Vincere',
        ['icon'] ='econ/items/queenofpain/guards_of_vincere/guards_of_vincere',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/guards_of_vincere/guards_of_vincere.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [5186] = {
        ['item_id'] =5186,
        ['name'] ='Mace of Vincere',
        ['icon'] ='econ/items/queenofpain/mace_of_vincere/mace_of_vincere',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/mace_of_vincere/mace_of_vincere.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [23743] = {
        ['item_id'] =23743,
        ['name'] ='Abyssal Kin Legs',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_legs/ti8_qop_bat_queen_legs',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_legs/ti8_qop_bat_queen_legs.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'legs',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'legs',
        },
        [4542] = {
        ['item_id'] =4542,
        ['name'] ='Dirk of the Wicked Succubus',
        ['icon'] ='econ/items/queenofpain/tpl_weapon_lvl1/tpl_weapon_lvl1',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/tpl_weapon_lvl1/tpl_weapon_lvl1.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [4550] = {
        ['item_id'] =4550,
        ['name'] ='Wraps of the Wicked Succubus',
        ['icon'] ='econ/items/queenofpain/tpl_shoulder_lvl1/tpl_shoulder_lvl1',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/tpl_shoulder_lvl1/tpl_shoulder_lvl1.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [7636] = {
        ['item_id'] =7636,
        ['name'] ='Horns of the Obsidian Nightmare',
        ['icon'] ='econ/items/queenofpain/obsidian_nightmare_head/obsidian_nightmare_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/obsidian_nightmare_head/obsidian_nightmare_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        
        [7191] = {
        ['item_id'] =7191,
        ['name'] ='Dagger of Twilight Shade',
        ['icon'] ='econ/items/queenofpain/twilight_shade_weapon/twilight_shade_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/twilight_shade_weapon/twilight_shade_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [5355] = {
        ['item_id'] =5355,
        ['name'] ='Chained Beauty',
        ['icon'] ='econ/items/queenofpain/unchained_restrained_beauty/unchained_restrained_beauty',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/unchained_restrained_beauty/unchained_restrained_beauty.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [5162] = {
        ['item_id'] =5162,
        ['name'] ='Maze of Anguish',
        ['icon'] ='econ/items/queenofpain/wingsofagony/wingsofagony',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/wingsofagony/wingsofagony.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [5359] = {
        ['item_id'] =5359,
        ['name'] ='Chained Spur',
        ['icon'] ='econ/items/queenofpain/unchained_poisonous_tail/unchained_poisonous_tail',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/unchained_poisonous_tail/unchained_poisonous_tail.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [5361] = {
        ['item_id'] =5361,
        ['name'] ='Chained Guard',
        ['icon'] ='econ/items/queenofpain/unchained_akashas_guard/unchained_akashas_guard',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/unchained_akashas_guard/unchained_akashas_guard.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [9863] = {
        ['item_id'] =9863,
        ['name'] ='Wings of the Abyssal Kin',
        ['icon'] ='econ/items/queenofpain/ti8_qop_bat_queen_back/ti8_qop_bat_queen_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/ti8_qop_bat_queen_back/ti8_qop_bat_queen_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [7190] = {
        ['item_id'] =7190,
        ['name'] ='Wings of Twilight Shade',
        ['icon'] ='econ/items/queenofpain/twilight_shade_back/twilight_shade_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/twilight_shade_back/twilight_shade_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [4543] = {
        ['item_id'] =4543,
        ['name'] ='Wings of the Wicked Succubus',
        ['icon'] ='econ/items/queenofpain/tpl_wing_lvl1/tpl_wing_lvl1',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/tpl_wing_lvl1/tpl_wing_lvl1.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        
        [7635] = {
        ['item_id'] =7635,
        ['name'] ='Pauldrons of the Obsidian Nightmare',
        ['icon'] ='econ/items/queenofpain/obsidian_nightmare_shoulder/obsidian_nightmare_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/obsidian_nightmare_shoulder/obsidian_nightmare_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [7637] = {
        ['item_id'] =7637,
        ['name'] ='Blade of the Obsidian Nightmare',
        ['icon'] ='econ/items/queenofpain/obsidian_nightmare_weapon/obsidian_nightmare_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/obsidian_nightmare_weapon/obsidian_nightmare_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        [7638] = {
        ['item_id'] =7638,
        ['name'] ='Wings of the Obsidian Nightmare',
        ['icon'] ='econ/items/queenofpain/obsidian_nightmare_back/obsidian_nightmare_back',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/obsidian_nightmare_back/obsidian_nightmare_back.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'back',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'back',
        },
        [26] = {
        ['item_id'] =26,
        ['name'] ='Queen of Pains Weapon',
        ['icon'] ='econ/heroes/queenofpain/queenofpain_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/queenofpain/queenofpain_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
        },
        
        [5588] = {
        ['item_id'] =5588,
        ['name'] ='Horns of Blight',
        ['icon'] ='econ/items/queenofpain/queenofpain_blightedagony_head/queenofpain_blightedagony_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/queenofpain/queenofpain_blightedagony_head/queenofpain_blightedagony_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        

--]]