 

my_game.heroes_particles = 
{
   -- "hero_juggernaut",
  --  "hero_phantom_assassin",
 --   "hero_huskar",
   -- "hero_nevermore",
 --   "hero_queenofpain",
  --  "hero_terrorblade",
   -- "hero_bristleback",
 --   "hero_puck",
--    "hero_legion_commander",
 --   "hero_void_spirit",
--    "hero_ember_spirit",
 --   "hero_pudge",
--    "hero_pudge_cute",
 --   "hero_hoodwink",
--    "hero_skeletonking",
--    "hero_lina",
--    "hero_troll_warlord",
--    "hero_axe",
 --   "hero_alchemist",
--    "hero_anti_mage",
--    "hero_ogre_magi",
 --   "hero_primal_beast",
 --   "hero_marci",
 --   "hero_templar_assassin",
 --   "hero_bloodseeker",
--    "hero_monkey_king",
--    "hero_mars",
--    "hero_zuus",
--    "hero_leshrac",
 --   "hero_crystalmaiden",
 --   "hero_snapfire",
 --   "hero_sven"

}




my_game.heroes_items_particles = 
{
  --  "juggernaut",
 --   "phantom_assassin",
 --   "huskar",
 --   "shadow_fiend",
 --   "queen_of_pain",
 --   "terrorblade",
 --   "bristleback",
  --  "puck",
    --"legion",
--    "void_spirit",
 --   "ember_spirit",
--    "pudge",
--    "wraith_king",
--    "lina",
--    "troll_warlord",
--    "axe",
 --   "alchemist",
  --  "ogre_magi",
 --   "anti_mage",
--    "primal_beast",
--    "marci",
--    "templar_assassin",
--    "bloodseeker",
 --   "monkey_king",
--    "mars",
--    "zeus",
 --   "leshrac",
--    "crystal_maiden",
--    "snapfire",
 --   "sven"
}




local usefull = 
{
    "particles/pa_heal.vpcf",
    "particles/pa_blur.vpcf",
    "particles/jugg_double_.vpcf",
    "particles/jugg_damage.vpcf",
    "particles/jugger_double.vpcf",
    "particles/qop_order_attack.vpcf",
    "particles/brist_shield.vpcf",

}





my_game.Particles = 
{

"particles/items3_fx/blink_swift_buff.vpcf",
"particles/units/heroes/hero_oracle/oracle_purifyingflames.vpcf",
"particles/items2_fx/sange_maim.vpcf",
"particles/generic_gameplay/generic_break.vpcf",
"particles/items3_fx/silver_edge.vpcf",
"particles/items3_fx/star_emblem.vpcf",
"particles/items3_fx/star_emblem_friend_shield.vpcf",
"particles/items4_fx/ascetic_cap.vpcf",
"particles/lc_odd_charge_mark.vpcf",
"particles/status_fx/status_effect_forcestaff.vpcf",
"particles/generic_gameplay/generic_silenced.vpcf",
"particles/generic_gameplay/generic_silenced_lanecreeps.vpcf",
"particles/generic_gameplay/generic_lifesteal.vpcf",
"particles/generic_gameplay/generic_sleep.vpcf",
"particles/items2_fx/manta_phase.vpcf",
"particles/generic_gameplay/generic_stunned.vpcf",
"particles/units/heroes/hero_snapfire/hero_snapfire_ultimate_calldown.vpcf",
"particles/generic_gameplay/rune_haste_owner.vpcf",
"particles/items3_fx/octarine_core_lifesteal.vpcf",
"particles/items_fx/black_king_bar_avatar.vpcf",
"particles/units/heroes/hero_pangolier/pangolier_tailthump_buff.vpcf",
"particles/units/heroes/hero_pangolier/pangolier_tailthump_buff_streaks.vpcf",
"particles/units/heroes/hero_pangolier/pangolier_tailthump_buff_egg.vpcf",
"particles/duel_wall.vpcf",
"particles/items5_fx/minotaur_horn.vpcf",
"particles/items_fx/force_staff.vpcf",
"particles/items4_fx/spirit_vessel_damage.vpcf",
"particles/generic_gameplay/generic_manaburn.vpcf",
"particles/generic_gameplay/rune_doubledamage_owner.vpcf",
"particles/items2_fx/medallion_of_courage_friend_shield.vpcf",
"particles/hero_spawn_hero_level_1.vpcf",
"particles/hero_spawn_hero_level_2.vpcf",
"particles/hero_spawn_hero_level_3.vpcf",
"particles/hero_spawn_hero_level_4.vpcf",
"particles/hero_spawn_hero_level_5.vpcf",
"particles/hero_spawn_hero_level_6.vpcf",
"particles/econ/events/ti5/teleport_end_lvl2_ti5.vpcf",
"particles/econ/events/ti10/teleport/teleport_start_ti10_lvl1_rewardline.vpcf",
"particles/econ/events/ti9/shovel_smoke_cloud.vpcf",

"particles/red_zone.vpcf",
"particles/lina_timer.vpcf",
"particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_hit.vpcf",
"particles/units/heroes/hero_sniper/sniper_headshot_slow.vpcf",
"particles/legion_duel_ring.vpcf",


"particles/rare_orb_patrol.vpcf",
"particles/cleance_blade.vpcf",
"particles/spell_breaker.vpcf", 
"particles/items2_fx/satanic_buff.vpcf",
"particles/roshan_meteor_.vpcf",
"particles/roshan_meteor_cast_.vpcf",
"particles/roshan_meteor_spell_.vpcf",
"particles/silver_edge_speed_.vpcf",
"particles/msg_fx/msg_miss.vpcf",
"particles/generic_gameplay/generic_purge.vpcf",
"particles/world_outpost/world_outpost_channel.vpcf",
"particles/items2_fx/teleport_start.vpcf",
"particles/items2_fx/teleport_end.vpcf",
"particles/world_outpost/world_outpost_dire_ambient.vpcf",
"particles/world_outpost/world_outpost_radiant_ambient.vpcf",
"particles/neutral_fx/neutral_centaur_khan_war_stomp.vpcf",
"particles/neutral_fx/mud_golem_hurl_boulder.vpcf",
"particles/neutral_fx/harpy_chain_lightning.vpcf",
"particles/neutral_fx/thunder_lizard_frenzy.vpcf",
"particles/neutral_fx/ogre_magi_frost_armor.vpcf",
"particles/generic_gameplay/generic_has_quest.vpcf",
"particles/neutral_fx/satyr_hellcaller.vpcf",
"particles/creatures/enraged_wildkin/enraged_wildkin_tornado.vpcf",
"particles/neutral_fx/ursa_thunderclap.vpcf",
"particles/units/heroes/hero_abaddon/abaddon_curse_counter_stack.vpcf",
"particles/units/heroes/hero_abaddon/abaddon_curse_frostmourne_debuff.vpcf",
"particles/units/heroes/hero_abaddon/abaddon_frost_buff.vpcf",
"particles/units/heroes/hero_abaddon/abaddon_borrowed_time_heal.vpcf",
"particles/units/heroes/hero_abaddon/abaddon_borrowed_time.vpcf",
"particles/status_fx/status_effect_abaddon_borrowed_time.vpcf",
"particles/units/heroes/hero_arc_warden/arc_warden_magnetic.vpcf",
"particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_blinding_light_aoe.vpcf",
"particles/econ/items/drow/drow_bow_monarch/drow_frost_arrow_monarch.vpcf",
"particles/units/heroes/hero_drow/drow_base_attack.vpcf",
"particles/creatures/quill_beast/test_model_cluster_linear_projectile.vpcf",
"particles/units/heroes/hero_centaur/centaur_double_edge_phase.vpcf",
"particles/units/heroes/hero_centaur/centaur_double_edge.vpcf",
"particles/units/heroes/hero_centaur/centaur_warstomp.vpcf",
"particles/econ/items/dazzle/dazzle_dark_light_weapon/dazzle_dark_shallow_grave.vpcf",
"particles/units/heroes/hero_winter_wyvern/wyvern_cold_embrace_buff.vpcf",
"particles/frostbitten_strike.vpcf",
"particles/generic_gameplay/generic_slowed_cold.vpcf",
"particles/units/heroes/hero_undying/undying_decay.vpcf",
"particles/status_fx/status_effect_frost_lich.vpcf",
"particles/units/heroes/hero_lich/lich_ice_spire.vpcf",
"particles/units/heroes/hero_lich/lich_frost_armor.vpcf",
"particles/units/heroes/hero_lich/lich_chain_frost.vpcf",
"particles/units/heroes/hero_lina/lina_death.vpcf",
"particles/econ/items/omniknight/hammer_ti6_immortal/omniknight_purification_ti6_immortal.vpcf",
"particles/units/heroes/hero_crystalmaiden/maiden_frostbite_buff.vpcf",
"particles/act_2/ogre_seal_suprise.vpcf",
"particles/neutral_fx/roshan_slam.vpcf",
"particles/neutral_fx/roshan_death.vpcf",
"particles/neutral_fx/prowler_shaman_shamanistic_ward.vpcf",
"particles/neutral_fx/neutral_prowler_shaman_stomp.vpcf",
"particles/items2_fx/medallion_of_courage_friend.vpcf",
"particles/siege_fx/siege_good_death_01.vpcf",
"particles/siege_fx/siege_bad_death_01.vpcf",
"particles/units/heroes/hero_silencer/silencer_last_word_status.vpcf",
"particles/units/heroes/hero_silencer/silencer_last_word_dmg.vpcf",
"particles/units/heroes/hero_slardar/slardar_amp_damage.vpcf",
"particles/units/heroes/hero_slardar/slardar_crush.vpcf",
"particles/units/heroes/hero_slardar/slardar_water_puddle.vpcf",
"particles/units/heroes/hero_broodmother/broodmother_incapacitatingbite_debuff.vpcf",
"particles/units/heroes/hero_viper/viper_nethertoxin.vpcf",
"particles/units/heroes/hero_techies/techies_remote_mines_detonate.vpcf",
"particles/units/heroes/hero_techies/techies_blast_off.vpcf",
"particles/generic_gameplay/generic_disarm.vpcf",
"particles/units/heroes/hero_treant/treant_livingarmor.vpcf",
"particles/units/heroes/hero_treant/treant_leech_seed.vpcf",
"particles/units/heroes/hero_treant/treant_leech_seed_damage_pulse.vpcf",
"particles/econ/items/lich/frozen_chains_ti6/lich_frozenchains_frostnova.vpcf",
"particles/units/heroes/hero_lycan/lycan_howl_cast.vpcf",
"particles/units/heroes/hero_lone_druid/lone_druid_battle_cry_overhead.vpcf",
"particles/econ/items/sven/sven_ti7_sword/sven_ti7_sword_spell_great_cleave.vpcf",

"particles/econ/items/silencer/silencer_ti6/silencer_last_word_ti6_silence.vpcf",
"particles/units/heroes/hero_centaur/centaur_stampede_overhead.vpcf",

"particles/units/heroes/hero_leshrac/leshrac_split_earth.vpcf",
"particles/units/heroes/hero_razor/razor_plasmafield.vpcf",
"particles/dire_plasma.vpcf",
"particles/radiant_resist.vpcf",
"particles/radiant_stun.vpcf",
"particles/radiant_plasma.vpcf",
"particles/dire_resist.vpcf",
"particles/dire_stun.vpcf",
"particles/world_shrine/dire_shrine_ambient.vpcf",
"particles/portals/portal_ground_spawn_endpoint.vpcf",
"particles/neutral_fx/roshan_spawn.vpcf",
"particles/duel_stun.vpcf",
"particles/duel_timer.vpcf",
"particles/gray_drop.vpcf",
"particles/orange_drop.vpcf",
"particles/purple_drop.vpcf",
"particles/blue_drop.vpcf",
"particles/units/heroes/hero_abaddon/abaddon_aphotic_shield_2.vpcf",
"particles/units/heroes/hero_tinker/tinker_defense_matrix.vpcf",
"particles/units/heroes/hero_magnataur/magnataur_empower_cleave_effect.vpcf",
"particles/fullhp_resist2.vpcf",
"particles/units/heroes/hero_phoenix/phoenix_supernova_reborn.vpcf",
"particles/items5_fx/repair_kit.vpcf",
"particles/econ/events/ti10/radiance_owner_ti10_glow.vpcf",
"particles/shrine/capture_point_ring_overthrow.vpcf",
"particles/shrine/capture_point_ring_clock_overthrow.vpcf",
"particles/econ/items/items_fx/lantern_of_sight_controlled.vpcf",
"particles/shrine/haste_zone.vpcf"


}
