return
{
    [23096] = 
    {
        ['item_id'] =23096,
        ['name'] ='Voidstorm Asylum Helm',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_head',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_head.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = 'particles/econ/items/razor/razor_arcana/razor_arcana_head_ambient.vpcf',
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = {[0] = {'SetParticleControl', 'default'}}
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{23096, "#8567e6"}, {2309699, "#69fab4"}},
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [23098] = 
    {
        ['item_id'] =23098,
        ['name'] ='Voidstorm Asylum Bracers',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_arms',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{23098, "#8567e6"}, {2309899, "#69fab4"}},
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [23099] = 
    {
        ['item_id'] =23099,
        ['name'] ='Voidstorm Asylum Belt',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_belt',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{23099, "#8567e6"}, {2309999, "#69fab4"}},
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [23095] = 
    {
        ['item_id'] =23095,
        ['name'] ='Voidstorm Asylum Tormentor',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_weapon',
        ['price'] = 15000,
        ['MaterialGroup'] = "default",
        ["MaterialGroupItem"] = "default",
        ['HeroModel'] = "models/items/razor/razor_arcana/razor_arcana.vmdl",
        ['ArcanaAnim'] = nil,
        ['is_exclusive'] = 1,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_weapon.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = "particles/econ/items/razor/razor_arcana/razor_arcana_shield_ambient.vpcf",
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = 
                {
                    [0] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_shield_eye_fx"
                    },
                }
            },
            {
                ['ParticleName'] = "particles/econ/items/razor/razor_arcana/razor_arcana_weapon_ambient_control_points.vpcf",
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = 
                {
                    [1] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_01_fx"
                    },
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_02_fx"
                    },
                    [3] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_03_fx"
                    },
                    [4] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_04_fx"
                    },
                    [5] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_05_fx"
                    },
                    [6] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_06_fx"
                    },
                    [7] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_07_fx"
                    },
                }
            },
        },
        ['ParticlesHero'] = 
        {
            {
                ['ParticleName'] = "particles/econ/items/razor/razor_arcana/razor_arcana_base_ambient_game.vpcf",
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ['ControllPoints'] = 
                {
                    [0] = {'SetParticleControl', 'default',},
                    [1] = {'SetParticleControl', 'default',},
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_shield_eye_fx", "attach_hitloc"
                    },
                    [5] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_base_end_fx", "hero"
                    },
                }
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{23095, "#8567e6"}, {2309599, "#69fab4"}},
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_razor_arcana_custom",
        ['sets'] = 'razor_arcana',
    },
    [23097] = 
    {
        ['item_id'] =23097,
        ['name'] ='Voidstorm Asylum Armor',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_armor',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_armor.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = 'particles/econ/items/razor/razor_arcana/razor_arcana_shoulder_ambient.vpcf',
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = {[0] = {'SetParticleControl', 'default'}}
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = {{23097, "#8567e6"}, {2309799, "#69fab4"}},
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [2309599] = 
    {
        ['item_id'] =2309599,
        ['name'] ='Voidstorm Asylum Tormentor',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_weapon',
        ['price'] = 15000,
        ['HeroModel'] = "models/items/razor/razor_arcana/razor_arcana.vmdl",
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = "2",
        ["MaterialGroupItem"] = "2",
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_weapon.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = "particles/econ/items/razor/razor_arcana/razor_arcana_shield_v2_ambient.vpcf",
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = 
                {
                    [0] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_shield_eye_fx"
                    },
                }
            },
            {
                ['ParticleName'] = "particles/econ/items/razor/razor_arcana/razor_arcana_weapon_ambient_control_points_v2.vpcf",
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = 
                {
                    [1] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_01_fx"
                    },
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_02_fx"
                    },
                    [3] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_03_fx"
                    },
                    [4] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_04_fx"
                    },
                    [5] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_05_fx"
                    },
                    [6] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_06_fx"
                    },
                    [7] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip_07_fx"
                    },
                }
            },
        },
        ['ParticlesHero'] =
        {
            {
                ['ParticleName'] = "particles/econ/items/razor/razor_arcana/razor_arcana_base_ambient_game_v2.vpcf",
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ['ControllPoints'] = 
                {
                    [0] = {'SetParticleControl', 'default',},
                    [1] = {'SetParticleControl', 'default',},
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_shield_eye_fx", "attach_hitloc"
                    },
                    [5] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_base_end_fx", "hero"
                    },
                }
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{23095, "#8567e6"}, {2309599, "#69fab4"}},
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_razor_arcana_v2_custom",
        ['sets'] = 'rare',
    },
    [2309699] = 
    {
        ['item_id'] =2309699,
        ['name'] ='Voidstorm Asylum Helm',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_head',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_head.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = 'particles/econ/items/razor/razor_arcana/razor_arcana_head_ambient_v2.vpcf',
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = {[0] = {'SetParticleControl', 'default'}}
            },
        },
        ['BodyGroup'] = "arcana",
        ['BodyGroupStyle'] = 2,
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{23096, "#8567e6"}, {2309699, "#69fab4"}},
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [2309899] = 
    {
        ['item_id'] =2309899,
        ['name'] ='Voidstorm Asylum Bracers',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_arms',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ["MaterialGroupItem"] = "1",
        ['BodyGroup'] = "arcana",
        ['BodyGroupStyle'] = 2,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{23098, "#8567e6"}, {2309899, "#69fab4"}},
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [2309999] = 
    {
        ['item_id'] =2309999,
        ['name'] ='Voidstorm Asylum Belt',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_belt',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['BodyGroup'] = "arcana",
        ['BodyGroupStyle'] = 2,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{23099, "#8567e6"}, {2309999, "#69fab4"}},
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [2309799] = 
    {
        ['item_id'] =2309799,
        ['name'] ='Voidstorm Asylum Armor',
        ['icon'] ='econ/items/razor/razor_arcana/razor_arcana_armor',
        ['price'] = 0,
        ['HeroModel'] = nil,
        ['BodyGroup'] = "arcana",
        ['BodyGroupStyle'] = 2,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arcana/razor_arcana_armor.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = 'particles/econ/items/razor/razor_arcana/razor_arcana_shoulder_ambient_v2.vpcf',
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = {[0] = {'SetParticleControl', 'default'}}
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 1,
        ['OtherItemsBundle'] = {{23097, "#8567e6"}, {2309799, "#69fab4"}},
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'razor_arcana',
    },
    [6646] = 
    {
        ['item_id'] =6646,
        ['name'] ='Severing Crest',
        ['icon'] ='econ/items/razor/razor_helmet_blade/razor_helmet_blade',
        ['price'] = 2000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_helmet_blade/razor_helmet_blade.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = 'particles/econ/items/razor/razor_punctured_crest/razor_helmet_blade_ambient.vpcf',
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = 
                {
                    [0] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_head"
                    },
                }
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_razor_head_immortal_custom",
        ['sets'] = 'rare',
    },
    [6916] = 
    {
        ['item_id'] =6916,
        ['name'] ='Golden Severing Crest',
        ['icon'] ='econ/items/razor/razor_helmet_blade/razor_helmet_blade1',
        ['price'] = 4000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_helmet_blade/razor_helmet_blade_gold.vmdl',
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = 'particles/econ/items/razor/razor_punctured_crest_golden/razor_helmet_blade_ambient_golden.vpcf',
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = 
                {
                    [0] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_head"
                    },
                }
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_razor_head_immortal_custom_golden",
        ['sets'] = 'rare',
    },
    [8000] = 
    {
        ['item_id'] = 8000,
        ['name'] ='Severing Lash',
        ['icon'] ='econ/items/razor/severing_lash/mesh/severing_lash',
        ['price'] = 1000,
        ['HeroModel'] = "models/heroes/razor/razor.vmdl",
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/severing_lash/mesh/severing_lash.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['ParticlesItems'] = 
        {
            {
                ['ParticleName'] = 'particles/econ/items/razor/razor_ti6/razor_whip_ti6.vpcf',
                ['DefaultPattch'] = PATTACH_ABSORIGIN_FOLLOW,
                ['ControllPoints'] = 
                {
                    [0] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip"
                    },
                    [1] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip1"
                    },
                    [2] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip2"
                    },
                    [3] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip3"
                    },
                    [4] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip4"
                    },
                    [5] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_whip5"
                    },
                }
            },
        },
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_razor_weapon_last_custom",
        ['sets'] = 'rare',
    },

    [14812] = 
{
        ['item_id'] =14812,
        ['name'] ='Test of the Basilisk Lord - Armor',
        ['icon'] ='econ/items/razor/eight_headed_basilisk_armor/eight_headed_basilisk_armor',
        ['price'] = 1500,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eight_headed_basilisk_armor/eight_headed_basilisk_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'basilisklord',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/razor/razor_eight_basilisk/razor_eight_basilisk_armor_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
},
[14813] = 
{
        ['item_id'] =14813,
        ['name'] ='Test of the Basilisk Lord - Belt',
        ['icon'] ='econ/items/razor/eight_headed_basilisk_belt/eight_headed_basilisk_belt',
        ['price'] = 1500,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eight_headed_basilisk_belt/eight_headed_basilisk_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'basilisklord',
},
[14814] = 
{
        ['item_id'] =14814,
        ['name'] ='Test of the Basilisk Lord - Head',
        ['icon'] ='econ/items/razor/eight_headed_basilisk_head/eight_headed_basilisk_head',
        ['price'] = 1000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eight_headed_basilisk_head/eight_headed_basilisk_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'basilisklord',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/razor/razor_eight_basilisk/razor_eight_basilisk_head_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_L"
                    },
                    [1] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_R"
                    },
                }
            },
        },
},
[14759] = 
{
        ['item_id'] =14759,
        ['name'] ='Test of the Basilisk Lord - Arms',
        ['icon'] ='econ/items/razor/eight_headed_basilisk_arms/eight_headed_basilisk_arms',
        ['price'] = 1000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eight_headed_basilisk_arms/eight_headed_basilisk_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'basilisklord',
},
[14815] = 
{
        ['item_id'] =14815,
        ['name'] ='Test of the Basilisk Lord - Weapon',
        ['icon'] ='econ/items/razor/eight_headed_basilisk_weapon/eight_headed_basilisk_weapon',
        ['price'] = 1000,
        ['HeroModel'] = 'models/heroes/razor/razor.vmdl',
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eight_headed_basilisk_weapon/eight_headed_basilisk_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'basilisklord',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/razor/razor_eight_basilisk/razor_eight_basilisk_weapon_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
},

[19500] = 
{
        ['item_id'] =19500,
        ['name'] ='Cruel Assemblage Armor',
        ['icon'] ='econ/items/razor/energy_meteorite_armor/energy_meteorite_armor',
        ['price'] = 1200,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/energy_meteorite_armor/energy_meteorite_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'cruelassemblage',
},
[19501] = 
{
        ['item_id'] =19501,
        ['name'] ='Cruel Assemblage Arms',
        ['icon'] ='econ/items/razor/energy_meteorite_arms/energy_meteorite_arms',
        ['price'] = 800,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/energy_meteorite_arms/energy_meteorite_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'cruelassemblage',
},
[19502] = 
{
        ['item_id'] =19502,
        ['name'] ='Cruel Assemblage Belt',
        ['icon'] ='econ/items/razor/energy_meteorite_belt/energy_meteorite_belt',
        ['price'] = 1200,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/energy_meteorite_belt/energy_meteorite_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'cruelassemblage',
},
[19503] = 
{
        ['item_id'] =19503,
        ['name'] ='Cruel Assemblage Head',
        ['icon'] ='econ/items/razor/energy_meteorite_head/energy_meteorite_head',
        ['price'] = 1000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/energy_meteorite_head/energy_meteorite_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'cruelassemblage',
},
[19505] = 
{
        ['item_id'] =19505,
        ['name'] ='Cruel Assemblage Weapon',
        ['icon'] ='econ/items/razor/energy_meteorite_weapon/energy_meteorite_weapon',
        ['price'] = 800,
        ['HeroModel'] = 'models/heroes/razor/razor.vmdl',
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/energy_meteorite_weapon/energy_meteorite_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'cruelassemblage',
},

[18130] = 
{
        ['item_id'] =18130,
        ['name'] ='Head of the Forlorn Maze',
        ['icon'] ='econ/items/razor/eternal_torturer_head/eternal_torturer_head',
        ['price'] = 300,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eternal_torturer_head/eternal_torturer_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'forlornmaze',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/razor/razor_fall20_eternal_torturer/razor_fall20_eternal_torturer_head.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_head"
                    },
                }
            },
        },
},
[18131] = 
{
        ['item_id'] =18131,
        ['name'] ='Belt of the Forlorn Maze',
        ['icon'] ='econ/items/razor/eternal_torturer_belt/eternal_torturer_belt',
        ['price'] = 400,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eternal_torturer_belt/eternal_torturer_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'forlornmaze',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/razor/razor_fall20_eternal_torturer/razor_fall20_eternal_torturer_belt.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                }
            },
        },
},
[18132] = 
{
        ['item_id'] =18132,
        ['name'] ='Armor of the Forlorn Maze',
        ['icon'] ='econ/items/razor/eternal_torturer_armor/eternal_torturer_armor',
        ['price'] = 100,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eternal_torturer_armor/eternal_torturer_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'forlornmaze',
},
[18133] = 
{
        ['item_id'] =18133,
        ['name'] ='Arms of the Forlorn Maze',
        ['icon'] ='econ/items/razor/eternal_torturer_arms/eternal_torturer_arms',
        ['price'] = 100,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eternal_torturer_arms/eternal_torturer_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'forlornmaze',
},
[18227] = 
{
        ['item_id'] =18227,
        ['name'] ='Whip of the Forlorn Maze',
        ['icon'] ='econ/items/razor/eternal_torturer_weapon/eternal_torturer_weapon',
        ['price'] = 100,
        ['HeroModel'] = 'models/heroes/razor/razor.vmdl',
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/eternal_torturer_weapon/eternal_torturer_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'forlornmaze',
},
}

-- Severing last
-- particles/econ/items/razor/razor_punctured_crest/razor_static_link_blade.vpcf

-- Golden
-- particles/econ/items/razor/razor_punctured_crest_golden/razor_static_link_blade_golden.vpcf

-- Weapon
-- particles/econ/items/razor/razor_ti6/razor_plasmafield_ti6.vpcf


    --[[
    [4986] = {
        ['item_id'] =4986,
        ['name'] ='Helm of the Twisted Arc',
        ['icon'] ='econ/items/razor/razor_head_dom_of_underscape/razor_head_dom_of_underscape',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_head_dom_of_underscape/razor_head_dom_of_underscape.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [4987] = {
        ['item_id'] =4987,
        ['name'] ='Twisted Arc',
        ['icon'] ='econ/items/razor/razor_weapon_dom_of_underscape/razor_weapon_dom_of_underscape',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_weapon_dom_of_underscape/razor_weapon_dom_of_underscape.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [5342] = {
        ['item_id'] =5342,
        ['name'] ='Storm-Stealers Armor',
        ['icon'] ='econ/items/razor/razor_armor_bindings/razor_armor_bindings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_armor_bindings/razor_armor_bindings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [8680] = {
        ['item_id'] =8680,
        ['name'] ='Whip of the Overseer',
        ['icon'] ='econ/items/razor/maze_watcher_weapon/maze_watcher_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_watcher_weapon/maze_watcher_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [5873] = {
        ['item_id'] =5873,
        ['name'] ='Grand Helm of the Narrow Maze',
        ['icon'] ='econ/items/razor/razor_helmet_grand/razor_helmet_grand',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_helmet_grand/razor_helmet_grand.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [5362] = {
        ['item_id'] =5362,
        ['name'] ='Storm-Stealers Helm',
        ['icon'] ='econ/items/razor/razor_head_bindings/razor_head_bindings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_head_bindings/razor_head_bindings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        
        [8959] = {
        ['item_id'] =8959,
        ['name'] ='Chestplate of the Guardian Construct',
        ['icon'] ='econ/items/razor/apostle_of_the_tempest_armor/apostle_of_the_tempest_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/apostle_of_the_tempest_armor/apostle_of_the_tempest_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [8960] = {
        ['item_id'] =8960,
        ['name'] ='Helm of the Guardian Construct',
        ['icon'] ='econ/items/razor/apostle_of_the_tempest_head/apostle_of_the_tempest_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/apostle_of_the_tempest_head/apostle_of_the_tempest_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        
        
        [340] = {
        ['item_id'] =340,
        ['name'] ='Razors Weapon',
        ['icon'] ='econ/heroes/razor/razor_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/razor/razor_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [341] = {
        ['item_id'] =341,
        ['name'] ='Razors Head',
        ['icon'] ='econ/heroes/razor/razor_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/razor/razor_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [342] = {
        ['item_id'] =342,
        ['name'] ='Razors Armor',
        ['icon'] ='econ/heroes/razor/razor_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/razor/razor_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [343] = {
        ['item_id'] =343,
        ['name'] ='Razors Bracers',
        ['icon'] ='econ/heroes/razor/razor_bracers',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/razor/razor_bracers.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        [12810] = {
        ['item_id'] =12810,
        ['name'] ='Barding of the Maze Keeper',
        ['icon'] ='econ/items/razor/frostivus2018_razor_thundersnow_belt/frostivus2018_razor_thundersnow_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/frostivus2018_razor_thundersnow_belt/frostivus2018_razor_thundersnow_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [12811] = {
        ['item_id'] =12811,
        ['name'] ='Lash of the Maze Keeper',
        ['icon'] ='econ/items/razor/frostivus2018_razor_thundersnow_weapon/frostivus2018_razor_thundersnow_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/frostivus2018_razor_thundersnow_weapon/frostivus2018_razor_thundersnow_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [12813] = {
        ['item_id'] =12813,
        ['name'] ='Arms of the Maze Keeper',
        ['icon'] ='econ/items/razor/frostivus2018_razor_thundersnow_arms/frostivus2018_razor_thundersnow_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/frostivus2018_razor_thundersnow_arms/frostivus2018_razor_thundersnow_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        [12814] = {
        ['item_id'] =12814,
        ['name'] ='Armor of the Maze Keeper',
        ['icon'] ='econ/items/razor/frostivus2018_razor_thundersnow_armor/frostivus2018_razor_thundersnow_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/frostivus2018_razor_thundersnow_armor/frostivus2018_razor_thundersnow_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        
        
        [9353] = {
        ['item_id'] =9353,
        ['name'] ='Mask of the Lightning Lord',
        ['icon'] ='econ/items/razor/empire_of_the_lightning_head/empire_of_the_lightning_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/empire_of_the_lightning_head/empire_of_the_lightning_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        
        [9354] = {
        ['item_id'] =9354,
        ['name'] ='Plate of the Lightning Lord',
        ['icon'] ='econ/items/razor/empire_of_the_lightning_lord_armor/empire_of_the_lightning_lord_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/empire_of_the_lightning_lord_armor/empire_of_the_lightning_lord_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        
        [9355] = {
        ['item_id'] =9355,
        ['name'] ='Conduit of the Lightning Lord',
        ['icon'] ='econ/items/razor/empire_of_the_lightning_lord_belt/empire_of_the_lightning_lord_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/empire_of_the_lightning_lord_belt/empire_of_the_lightning_lord_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [9356] = {
        ['item_id'] =9356,
        ['name'] ='Rings of the Lightning Lord',
        ['icon'] ='econ/items/razor/empire_of_the_lightning_lord_arms/empire_of_the_lightning_lord_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/empire_of_the_lightning_lord_arms/empire_of_the_lightning_lord_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        [9357] = {
        ['item_id'] =9357,
        ['name'] ='Spark of the Lightning Lord',
        ['icon'] ='econ/items/razor/empire_of_the_lightning_lord_weapon/empire_of_the_lightning_lord_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/empire_of_the_lightning_lord_weapon/empire_of_the_lightning_lord_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [23734] = {
        ['item_id'] =23734,
        ['name'] ='Amethyst Influx - Arms',
        ['icon'] ='econ/items/razor/fulminous_punisher_arms/fulminous_punisher_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/fulminous_punisher_arms/fulminous_punisher_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        
        [7476] = {
        ['item_id'] =7476,
        ['name'] ='Bracers of the Revenant',
        ['icon'] ='econ/items/razor/shard_revenant_arms/shard_revenant_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/shard_revenant_arms/shard_revenant_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        [7477] = {
        ['item_id'] =7477,
        ['name'] ='Armor of the Revenant',
        ['icon'] ='econ/items/razor/shard_revenant_armor/shard_revenant_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/shard_revenant_armor/shard_revenant_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [7478] = {
        ['item_id'] =7478,
        ['name'] ='Helm of the Revenant',
        ['icon'] ='econ/items/razor/shard_revenant_head/shard_revenant_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/shard_revenant_head/shard_revenant_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [7479] = {
        ['item_id'] =7479,
        ['name'] ='Skirt of the Revenant',
        ['icon'] ='econ/items/razor/shard_revenant_belt/shard_revenant_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/shard_revenant_belt/shard_revenant_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [7480] = {
        ['item_id'] =7480,
        ['name'] ='Whip of the Revenant',
        ['icon'] ='econ/items/razor/shard_revenant_weapon/shard_revenant_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/shard_revenant_weapon/shard_revenant_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [5349] = {
        ['item_id'] =5349,
        ['name'] ='Storm-Stealers Bracers',
        ['icon'] ='econ/items/razor/razor_arms_bindings/razor_arms_bindings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arms_bindings/razor_arms_bindings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        [5357] = {
        ['item_id'] =5357,
        ['name'] ='Storm-Stealers Belt',
        ['icon'] ='econ/items/razor/razor_belt_bindings/razor_belt_bindings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_belt_bindings/razor_belt_bindings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [12575] = {
        ['item_id'] =12575,
        ['name'] ='Helm of the Narrow Fates',
        ['icon'] ='econ/items/razor/maze_master_head/maze_master_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_master_head/maze_master_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [12576] = {
        ['item_id'] =12576,
        ['name'] ='Bracers of the Narrow Fates',
        ['icon'] ='econ/items/razor/maze_master_arms/maze_master_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_master_arms/maze_master_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        [8613] = {
        ['item_id'] =8613,
        ['name'] ='Cuirass of the Overseer',
        ['icon'] ='econ/items/razor/maze_watcher_armor/maze_watcher_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_watcher_armor/maze_watcher_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [8967] = {
        ['item_id'] =8967,
        ['name'] ='Skirt of the Guardian Construct',
        ['icon'] ='econ/items/razor/apostle_of_the_tempest_belt/apostle_of_the_tempest_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/apostle_of_the_tempest_belt/apostle_of_the_tempest_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [8968] = {
        ['item_id'] =8968,
        ['name'] ='Bracers of the Guardian Construct',
        ['icon'] ='econ/items/razor/apostle_of_the_tempest_arms/apostle_of_the_tempest_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/apostle_of_the_tempest_arms/apostle_of_the_tempest_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        [8969] = {
        ['item_id'] =8969,
        ['name'] ='Whip of the Guardian Construct',
        ['icon'] ='econ/items/razor/apostle_of_the_tempest_weapon/apostle_of_the_tempest_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/apostle_of_the_tempest_weapon/apostle_of_the_tempest_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [14845] = {
        ['item_id'] =14845,
        ['name'] ='Heinous Exultation - Arms',
        ['icon'] ='econ/items/razor/razor_silver_revenant_arms/razor_silver_revenant_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_silver_revenant_arms/razor_silver_revenant_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        
        [23736] = {
        ['item_id'] =23736,
        ['name'] ='Amethyst Influx - Head',
        ['icon'] ='econ/items/razor/fulminous_punisher_head/fulminous_punisher_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/fulminous_punisher_head/fulminous_punisher_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [23735] = {
        ['item_id'] =23735,
        ['name'] ='Amethyst Influx - Belt',
        ['icon'] ='econ/items/razor/fulminous_punisher_belt/fulminous_punisher_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/fulminous_punisher_belt/fulminous_punisher_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        
        [12578] = {
        ['item_id'] =12578,
        ['name'] ='Armor of the Narrow Fates',
        ['icon'] ='econ/items/razor/maze_master_armor/maze_master_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_master_armor/maze_master_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [5380] = {
        ['item_id'] =5380,
        ['name'] ='Storm-Stealers Whip',
        ['icon'] ='econ/items/razor/razor_weapon_bindings/razor_weapon_bindings',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_weapon_bindings/razor_weapon_bindings.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [14843] = {
        ['item_id'] =14843,
        ['name'] ='Heinous Exultation - Weapon',
        ['icon'] ='econ/items/razor/razor_silver_revenant_weapon/razor_silver_revenant_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_silver_revenant_weapon/razor_silver_revenant_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [14846] = {
        ['item_id'] =14846,
        ['name'] ='Heinous Exultation - Belt',
        ['icon'] ='econ/items/razor/razor_silver_revenant_belt/razor_silver_revenant_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_silver_revenant_belt/razor_silver_revenant_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [8615] = {
        ['item_id'] =8615,
        ['name'] ='Bracers of the Overseer',
        ['icon'] ='econ/items/razor/maze_watcher_arms/maze_watcher_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_watcher_arms/maze_watcher_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        
        [8608] = {
        ['item_id'] =8608,
        ['name'] ='Helm of the Overseer',
        ['icon'] ='econ/items/razor/maze_watcher_head/maze_watcher_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_watcher_head/maze_watcher_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [23738] = {
        ['item_id'] =23738,
        ['name'] ='Amethyst Influx - Weapon',
        ['icon'] ='econ/items/razor/fulminous_punisher_weapon/fulminous_punisher_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/fulminous_punisher_weapon/fulminous_punisher_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
        [23739] = {
        ['item_id'] =23739,
        ['name'] ='Amethyst Influx - Armor',
        ['icon'] ='econ/items/razor/fulminous_punisher_armor/fulminous_punisher_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/fulminous_punisher_armor/fulminous_punisher_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [8614] = {
        ['item_id'] =8614,
        ['name'] ='Belt of the Overseer',
        ['icon'] ='econ/items/razor/maze_watcher_belt/maze_watcher_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_watcher_belt/maze_watcher_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [344] = {
        ['item_id'] =344,
        ['name'] ='Razors Robe',
        ['icon'] ='econ/heroes/razor/razor_robe',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/razor/razor_robe.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        
        [12812] = {
        ['item_id'] =12812,
        ['name'] ='Helm of the Maze Keeper',
        ['icon'] ='econ/items/razor/frostivus2018_razor_thundersnow_head/frostivus2018_razor_thundersnow_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/frostivus2018_razor_thundersnow_head/frostivus2018_razor_thundersnow_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        [4983] = {
        ['item_id'] =4983,
        ['name'] ='Armor of the Twisted Arc',
        ['icon'] ='econ/items/razor/razor_armor_dom_of_underscape/razor_armor_dom_of_underscape',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_armor_dom_of_underscape/razor_armor_dom_of_underscape.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [4984] = {
        ['item_id'] =4984,
        ['name'] ='Belt of the Twisted Arc',
        ['icon'] ='econ/items/razor/razor_belt_dom_of_underscape/razor_belt_dom_of_underscape',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_belt_dom_of_underscape/razor_belt_dom_of_underscape.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [4985] = {
        ['item_id'] =4985,
        ['name'] ='Bracers of the Twisted Arc',
        ['icon'] ='econ/items/razor/razor_arms_dom_of_underscape/razor_arms_dom_of_underscape',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_arms_dom_of_underscape/razor_arms_dom_of_underscape.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
    },
        
        [14847] = {
        ['item_id'] =14847,
        ['name'] ='Heinous Exultation - Armor',
        ['icon'] ='econ/items/razor/razor_silver_revenant_armor/razor_silver_revenant_armor',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_silver_revenant_armor/razor_silver_revenant_armor.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'armor',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'armor',
    },
        [12577] = {
        ['item_id'] =12577,
        ['name'] ='Belt of the Narrow Fates',
        ['icon'] ='econ/items/razor/maze_master_belt/maze_master_belt',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_master_belt/maze_master_belt.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'belt',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'belt',
    },
        [14844] = {
        ['item_id'] =14844,
        ['name'] ='Heinous Exultation - Head',
        ['icon'] ='econ/items/razor/razor_silver_revenant_head/razor_silver_revenant_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/razor_silver_revenant_head/razor_silver_revenant_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
    },
        
        [12574] = {
        ['item_id'] =12574,
        ['name'] ='Whip of the Narrow Fates',
        ['icon'] ='econ/items/razor/maze_master_weapon/maze_master_weapon',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/razor/maze_master_weapon/maze_master_weapon.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'weapon',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'weapon',
    },
}
--]]