return
{
    [6996] = 
    {
        ['item_id'] =6996,
        ['name'] ='Demon Eater',
        ['icon'] ='econ/items/nevermore/shadowfiend_demon_eater',
        ['price'] = 15000,
        ['HeroModel'] = "models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl",
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] = 'models/heroes/shadow_fiend/head_arcana.vmdl',
        ["ParticlesHero"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [1] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_R0"
                    },
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_R1"
                    },
                    [3] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_R2"
                    },
                    [4] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_L0"
                    },
                    [5] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_L1"
                    },
                    [6] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_wing_L2"
                    },
                    [7] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_head"
                    },
                }
            },
            {
                ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient_eyes.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = 
                {
                    [1] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eyeL"
                    },
                    [2] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eyeR"
                    },
                }
            },
            {
                ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_trail.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ['IsHero'] = 1,
                ["ControllPoints"] = {},
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_shadow_fiend_arcana_custom",
        ['sets'] = 'rare',
    },
    [8259] = 
    {
        ['item_id'] =8259,
        ['name'] ='Arms of Desolation',
        ['icon'] ='econ/items/shadow_fiend/arms_deso/arms_deso',
        ['price'] = 2500,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/shadow_fiend/arms_deso/arms_deso.vmdl',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_desolation/shadow_fiend_desolation_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_arm_L", "hero"
                    },
                    [1] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_arm_R", "hero"
                    },
                }
            },
        },
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = "modifier_shadow_fiend_desolator_custom",
        ['sets'] = 'rare',
    },
    [9021] = 
    {
            ['item_id'] =9021,
            ['name'] ='Horns of Eternal Harvest',
            ['icon'] ='econ/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head',
            ['price'] = 1000,
            ["MaterialGroupItem"] = "0",
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head.vmdl',
            ["ParticlesItems"] = 
            {
                {
                    ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_ferrum/shadow_fiend_ferrum_head_ambient.vpcf",
                    ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                    ["ControllPoints"] = 
                    {
                        [0] = {"SetParticleControl", "default"},
                    }
                },
            },
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = {{9021, "#d8d8d8"}, {22845, "#9d4c78"}},
            ['SlotType'] = 'head',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'eternalharverst',
    },
    [9019] = 
    {
            ['item_id'] =9019,
            ['name'] ='Grips of Eternal Harvest',
            ['icon'] ='econ/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms',
            ['price'] = 1000,
            ["MaterialGroupItem"] = "0",
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = {{9019, "#d8d8d8"}, {22843, "#9d4c78"}},
            ['SlotType'] = 'arms',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'eternalharverst',
    },
    [9020] = 
    {
            ['item_id'] =9020,
            ['name'] ='Pauldrons of Eternal Harvest',
            ['icon'] ='econ/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder',
            ['price'] = 7000,
            ["ParticlesItems"] = 
            {
                {
                    ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_ferrum/shadow_fiend_ferrum_shoulder_ambient.vpcf",
                    ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                    ["ControllPoints"] = 
                    {
                        [0] = {"SetParticleControl", "default"},
                    }
                },
            },
            ["MaterialGroupItem"] = "0",
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = {{9020, "#d8d8d8"}, {22844, "#9d4c78"}},
            ['SlotType'] = 'shoulder',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'eternalharverst',
    },

    [13505] = 
    {
        ['item_id'] =13505,
        ['name'] ='Souls Tyrant Head',
        ['icon'] ='econ/items/nevermore/sf_souls_tyrant_head/sf_souls_tyrant_head',
        ['price'] = 1000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/sf_souls_tyrant_head/sf_souls_tyrant_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'soulstyrant',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_souls_tyrant/sf_souls_tyrant_head_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [1] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_eye_center"
                    },
                }
            },
        },
    },
    [13506] = 
    {
        ['item_id'] =13506,
        ['name'] ='Souls Tyrant Arms',
        ['icon'] ='econ/items/nevermore/sf_souls_tyrant_arms/sf_souls_tyrant_arms',
        ['price'] = 1000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/sf_souls_tyrant_arms/sf_souls_tyrant_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'soulstyrant',
    },
    [13507] = 
    {
        ['item_id'] =13507,
        ['name'] ='Souls Tyrant Shoulder',
        ['icon'] ='econ/items/nevermore/sf_souls_tyrant_shoulder/sf_souls_tyrant_shoulder',
        ['price'] = 2000,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/sf_souls_tyrant_shoulder/sf_souls_tyrant_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'soulstyrant',
        ["ParticlesItems"] = 
        {
            {
                ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_souls_tyrant/sf_souls_tyrant_shoulder_ambient.vpcf",
                ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                ["ControllPoints"] = 
                {
                    [0] = {"SetParticleControl", "default"},
                    [1] = 
                    {
                        'SetParticleControlEnt', PATTACH_POINT_FOLLOW,
                        "attach_shoulder_l"
                    },
                }
            },
        },
    },

    [12677] = 
    {
            ['item_id'] =12677,
            ['name'] ='Soul Corpulence - Shoulder',
            ['icon'] ='econ/items/nevermore/sf_immortal_flame_shoulder/sf_immortal_flame_shoulder',
            ['price'] = 2000,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/sf_immortal_flame_shoulder/sf_immortal_flame_shoulder.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'shoulder',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'soulcorplence',
    },
    [12678] = {
            ['item_id'] =12678,
            ['name'] ='Soul Corpulence - Head',
            ['icon'] ='econ/items/nevermore/sf_immortal_flame_head/sf_immortal_flame_head',
            ['price'] = 1000,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/sf_immortal_flame_head/sf_immortal_flame_head.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'head',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'soulcorplence',
    },
    [12679] = {
            ['item_id'] =12679,
            ['name'] ='Soul Corpulence - Arms',
            ['icon'] ='econ/items/nevermore/sf_immortal_flame_arms/sf_immortal_flame_arms',
            ['price'] = 1000,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/sf_immortal_flame_arms/sf_immortal_flame_arms.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'arms',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'soulcorplence',
    },
    [22845] = 
    {
            ['item_id'] =22845,
            ['name'] ='Spring Lineage Horns of Eternal Harvest',
            ['icon'] ='econ/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head1',
            ['price'] = 1,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 1,
            ['OtherItemsBundle'] = {{9021, "#FFFFFF"}, {22845, "#000000"}},
            ['SlotType'] = 'head',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ["MaterialGroupItem"] = "1",
            ['sets'] = 'eternalharverst',
            ["ParticlesItems"] = 
            {
                {
                    ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_ferrum/shadow_fiend_ferrum_head_ambient.vpcf",
                    ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                    ["ControllPoints"] = 
                    {
                        [0] = {"SetParticleControl", "default"},
                    }
                },
            },
    },
    [22844] = 
    {
            ['item_id'] =22844,
            ['name'] ='Spring Lineage Pauldrons of Eternal Harvest',
            ['icon'] ='econ/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder1',
            ['price'] = 1,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 1,
            ['OtherItemsBundle'] = {{9020, "#FFFFFF"}, {22844, "#000000"}},
            ['SlotType'] = 'shoulder',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ["MaterialGroupItem"] = "1",
            ['sets'] = 'eternalharverst',
            ["ParticlesItems"] = 
            {
                {
                    ["ParticleName"] = "particles/econ/items/shadow_fiend/sf_ferrum/shadow_fiend_ferrum_shoulder_ambient.vpcf",
                    ["DefaultPattch"] = PATTACH_ABSORIGIN_FOLLOW,
                    ["ControllPoints"] = 
                    {
                        [0] = {"SetParticleControl", "default"},
                    }
                },
            },
    },
    [22843] = 
    {
            ['item_id'] =22843,
            ['name'] ='Spring Lineage Grips of Eternal Harvest',
            ['icon'] ='econ/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms1',
            ['price'] = 1,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 1,
            ['OtherItemsBundle'] = {{9019, "#FFFFFF"}, {22843, "#000000"}},
            ['SlotType'] = 'arms',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ["MaterialGroupItem"] = "1",
            ['sets'] = 'eternalharverst',
    },
    [18034] = 
    {
            ['item_id'] =18034,
            ['name'] ='Twilight Effigy Arms',
            ['icon'] ='econ/items/nevermore/harvest_effigy_arms/harvest_effigy_arms',
            ['price'] = 300,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/harvest_effigy_arms/harvest_effigy_arms.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'arms',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'twilight_effigy',
    },
    [18035] = 
    {
            ['item_id'] =18035,
            ['name'] ='Twilight Effigy Head',
            ['icon'] ='econ/items/nevermore/harvest_effigy_head/harvest_effigy_head',
            ['price'] = 300,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/harvest_effigy_head/harvest_effigy_head.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'head',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'twilight_effigy',
    },
    [18036] = 
    {
            ['item_id'] =18036,
            ['name'] ='Twilight Effigy Armor',
            ['icon'] ='econ/items/nevermore/harvest_effigy_shoulder/harvest_effigy_shoulder',
            ['price'] = 400,
            ['HeroModel'] = nil,
            ['ArcanaAnim'] = nil,
            ['MaterialGroup'] = nil,
            ['ItemModel'] ='models/items/nevermore/harvest_effigy_shoulder/harvest_effigy_shoulder.vmdl',
            ['SetItems'] = nil,
            ['hide'] = 0,
            ['OtherItemsBundle'] = nil,
            ['SlotType'] = 'shoulder',
            ['RemoveDefaultItemsList'] = nil,
            ['Modifier'] = nil,
            ['sets'] = 'twilight_effigy',
    },
}

    --[[ 
    [9993] = {
        ['item_id'] =9993,
        ['name'] ='Murder of Souls Talons',
        ['icon'] ='econ/items/nevermore/nevermores_shade_arms/nevermores_shade_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/nevermores_shade_arms/nevermores_shade_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
        },
        [9994] = {
        ['item_id'] =9994,
        ['name'] ='Murder of Souls Crown',
        ['icon'] ='econ/items/nevermore/nevermores_shade_head/nevermores_shade_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/nevermores_shade_head/nevermores_shade_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [9995] = {
        ['item_id'] =9995,
        ['name'] ='Murder of Souls Shoulders',
        ['icon'] ='econ/items/nevermore/nevermores_shade_shoulder/nevermores_shade_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/nevermores_shade_shoulder/nevermores_shade_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [19841] = {
        ['item_id'] =19841,
        ['name'] ='King of Vipers Shoulder',
        ['icon'] ='econ/items/nevermore/king_of_vipers_shoulder/king_of_vipers_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/king_of_vipers_shoulder/king_of_vipers_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [19843] = {
        ['item_id'] =19843,
        ['name'] ='King of Vipers Head',
        ['icon'] ='econ/items/nevermore/king_of_vipers_head/king_of_vipers_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/king_of_vipers_head/king_of_vipers_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
  
        [488] = {
        ['item_id'] =488,
        ['name'] ='Shadow Fiends Arms',
        ['icon'] ='econ/heroes/shadow_fiend/shadow_fiend_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/shadow_fiend/shadow_fiend_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
        },
        [9494] = {
        ['item_id'] =9494,
        ['name'] ='Breastplate of the Fathomless Ravager',
        ['icon'] ='econ/items/nevermore/krakens_ravager_shoulder/krakens_ravager_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/krakens_ravager_shoulder/krakens_ravager_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [9496] = {
        ['item_id'] =9496,
        ['name'] ='Helm of the Fathomless Ravager',
        ['icon'] ='econ/items/nevermore/krakens_ravager_head/krakens_ravager_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/krakens_ravager_head/krakens_ravager_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [7279] = {
        ['item_id'] =7279,
        ['name'] ='Armor of the Diabolical Fiend',
        ['icon'] ='econ/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        
        [387] = {
        ['item_id'] =387,
        ['name'] ='Shadow Fiends Head',
        ['icon'] ='econ/heroes/shadow_fiend/shadow_fiend_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/shadow_fiend/shadow_fiend_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [22845] = {
        ['item_id'] =22845,
        ['name'] ='Spring Lineage Horns of Eternal Harvest',
        ['icon'] ='econ/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head1',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [9021] = {
        ['item_id'] =9021,
        ['name'] ='Horns of Eternal Harvest',
        ['icon'] ='econ/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [12677] = {
        ['item_id'] =12677,
        ['name'] ='Soul Corpulence - Shoulder',
        ['icon'] ='econ/items/nevermore/sf_immortal_flame_shoulder/sf_immortal_flame_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/sf_immortal_flame_shoulder/sf_immortal_flame_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [12678] = {
        ['item_id'] =12678,
        ['name'] ='Soul Corpulence - Head',
        ['icon'] ='econ/items/nevermore/sf_immortal_flame_head/sf_immortal_flame_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/sf_immortal_flame_head/sf_immortal_flame_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [12679] = {
        ['item_id'] =12679,
        ['name'] ='Soul Corpulence - Arms',
        ['icon'] ='econ/items/nevermore/sf_immortal_flame_arms/sf_immortal_flame_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/sf_immortal_flame_arms/sf_immortal_flame_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
        },
        [19844] = {
        ['item_id'] =19844,
        ['name'] ='King of Vipers Arms',
        ['icon'] ='econ/items/nevermore/king_of_vipers_arms/king_of_vipers_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/king_of_vipers_arms/king_of_vipers_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
        },
        [9019] = {
        ['item_id'] =9019,
        ['name'] ='Grips of Eternal Harvest',
        ['icon'] ='econ/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
        },
        [9020] = {
        ['item_id'] =9020,
        ['name'] ='Pauldrons of Eternal Harvest',
        ['icon'] ='econ/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },

        [7193] = {
        ['item_id'] =7193,
        ['name'] ='Arms of the Diabolical Fiend',
        ['icon'] ='econ/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
        },
        [486] = {
        ['item_id'] =486,
        ['name'] ='Shadow Fiends Shoulders',
        ['icon'] ='econ/heroes/shadow_fiend/shadow_fiend_shoulders',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'shoulder',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'shoulder',
        },
        [7188] = {
        ['item_id'] =7188,
        ['name'] ='Horns of the Diabolical Fiend',
        ['icon'] ='econ/items/nevermore/diabolical_fiend_head/diabolical_fiend_head',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'head',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'head',
        },
        [9495] = {
        ['item_id'] =9495,
        ['name'] ='Claws of the Fathomless Ravager',
        ['icon'] ='econ/items/nevermore/krakens_ravager_arms/krakens_ravager_arms',
        ['price'] = 1,
        ['HeroModel'] = nil,
        ['ArcanaAnim'] = nil,
        ['MaterialGroup'] = nil,
        ['ItemModel'] ='models/items/nevermore/krakens_ravager_arms/krakens_ravager_arms.vmdl',
        ['SetItems'] = nil,
        ['hide'] = 0,
        ['OtherItemsBundle'] = nil,
        ['SlotType'] = 'arms',
        ['RemoveDefaultItemsList'] = nil,
        ['Modifier'] = nil,
        ['sets'] = 'arms',
        },
}
]]--