return
{
    ["arms"] = 
    {
        "models/items/nevermore/krakens_ravager_arms/krakens_ravager_arms.vmdl",
		"models/items/nevermore/harvest_effigy_arms/harvest_effigy_arms.vmdl",
		"models/items/nevermore/sf_immortal_flame_arms/sf_immortal_flame_arms.vmdl",
		"models/items/nevermore/sf_souls_tyrant_arms/sf_souls_tyrant_arms.vmdl",
		"models/items/nevermore/nevermores_shade_arms/nevermores_shade_arms.vmdl",
		"models/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms.vmdl",
		"models/items/shadow_fiend/arms_deso/arms_deso.vmdl",
		"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl",
		"models/items/nevermore/king_of_vipers_arms/king_of_vipers_arms.vmdl",
		"models/heroes/shadow_fiend/shadow_fiend_arms.vmdl",
    },
    ["head"] =
    {
        "models/items/nevermore/krakens_ravager_head/krakens_ravager_head.vmdl",
		"models/items/nevermore/harvest_effigy_head/harvest_effigy_head.vmdl",
		"models/items/nevermore/king_of_vipers_head/king_of_vipers_head.vmdl",
		"models/items/nevermore/sf_immortal_flame_head/sf_immortal_flame_head.vmdl",
		"models/items/nevermore/sf_souls_tyrant_head/sf_souls_tyrant_head.vmdl",
		"models/heroes/shadow_fiend/head_arcana.vmdl",
		"models/items/nevermore/nevermores_shade_head/nevermores_shade_head.vmdl",
		"models/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head.vmdl",
		"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl",
		"models/heroes/shadow_fiend/shadow_fiend_head.vmdl",
    },
    ["shoulder"] = 
    {
        "models/items/nevermore/krakens_ravager_shoulder/krakens_ravager_shoulder.vmdl",
		"models/items/nevermore/harvest_effigy_shoulder/harvest_effigy_shoulder.vmdl",
		"models/items/nevermore/sf_immortal_flame_shoulder/sf_immortal_flame_shoulder.vmdl",
		"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl",
		"models/items/nevermore/sf_souls_tyrant_shoulder/sf_souls_tyrant_shoulder.vmdl",
		"models/items/nevermore/nevermores_shade_shoulder/nevermores_shade_shoulder.vmdl",
		"models/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder.vmdl",
        "models/items/nevermore/king_of_vipers_shoulder/king_of_vipers_shoulder.vmdl",
		"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl",
    },
}